@echo off
echo Testing this script...
start /wait /min cmd /C "C:\PROGRA~1\INTERN~1\iexplore.exe C:\Users\leek13\Documents\GitHub\PsychoPyParadigms\DoorTask\FortuneWheel\index16.html"
echo Continuing the script...